# Generated by Django 4.2.25 on 2025-11-16 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nautobottil', '0062_alter_circuitlogicalline_port_a'),
        ('nautobot_circuit_maintenance', '0013_rename_site_search_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitimpact',
            name='circuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nautobottil.circuitphysicalline'),
        ),
    ]
