# Generated by Django 4.2.25 on 2025-11-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_circuit_maintenance', '0014_alter_circuitimpact_circuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitmaintenance',
            name='external_reference',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
