# Generated by Django 4.2.25 on 2025-11-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_circuit_maintenance', '0015_circuitmaintenance_external_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitmaintenance',
            name='external_reference',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
